"""Add fields to Usuario model

Revision ID: 01447aefd7ff
Revises: d9094f1639e8
Create Date: 2026-01-23 22:28:14.888745

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01447aefd7ff'
down_revision: Union[str, Sequence[str], None] = 'd9094f1639e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('nombre', sa.String(), nullable=False))
    op.add_column('usuarios', sa.Column('estado', sa.Integer(), nullable=False))
    op.add_column('usuarios', sa.Column('creado_en', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('usuarios', sa.Column('modificado_en', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuarios', 'modificado_en')
    op.drop_column('usuarios', 'creado_en')
    op.drop_column('usuarios', 'estado')
    op.drop_column('usuarios', 'nombre')
    # ### end Alembic commands ###
