"""Update Empresa fields nombre and nit

Revision ID: beec60a5c3fe
Revises: eb0eea0be28f
Create Date: 2026-01-23 19:51:10.884011

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'beec60a5c3fe'
down_revision: Union[str, Sequence[str], None] = 'eb0eea0be28f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('empresas', sa.Column('nombre', sa.String(), nullable=False))
    op.add_column('empresas', sa.Column('nit', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'empresas', ['nit'])
    op.drop_column('empresas', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('empresas', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'empresas', type_='unique')
    op.drop_column('empresas', 'nit')
    op.drop_column('empresas', 'nombre')
    # ### end Alembic commands ###
