"""update config

Revision ID: d9094f1639e8
Revises: beec60a5c3fe
Create Date: 2026-01-23 20:16:50.547943

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9094f1639e8'
down_revision: Union[str, Sequence[str], None] = 'beec60a5c3fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('entity_configs', 'entity_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entity_configs', sa.Column('entity_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
